defaults: &defaults
  serviceName: image-handler-test
  region: 'us-east-1'
  environment: &defaults.environment
    DEFAULT_QUALITY: 75
    DEFAULT_COMPRESS_QUALITY: 45
    SLS_IGNORE: favicon.ico
    SLS_VALID_PATH_REGEX: '.*'
    MAX_IMAGE_WIDTH: 2000
    MAX_IMAGE_HEIGHT: 2000
    PNGQUANT_SPEED: 10
    DEFAULT_CACHE_CONTROL: 'max-age=2592000'

stages:
  dev:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: 'my-bucket/prefix/path'
      SECURITY_KEY: ''
      CUSTOM_DOMAIN: ''
      ACM_CERTIFICATE_ARN: ''
  prod:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: 'random-string-here'
      SECURITY_KEY: ''
      CUSTOM_DOMAIN: 'my.domain.com'
      ACM_CERTIFICATE_ARN: ''
